In [1]:
import numpy as np
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
aa = a.reshape(3,5)
aa

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
#陣列的維度
print(a.ndim)
print(aa.ndim) 

1
2


In [6]:
#陣列各維度大小
print(a.shape)
print(aa.shape) #(3, 5)代表3x5的矩陣

(15,)
(3, 5)


In [7]:
#陣列總元素個數
print(a.size)
print(aa.size)

15
15


In [8]:
#陣列每個元素的byte數
print(a.itemsize)
print(aa.itemsize)

4
4


In [9]:
#陣列元素類型
print(a.dtype)
print(aa.dtype)

int32
int32


In [11]:
b = np.array(["1", 2]) # <代表little-endian ; U1代表 unsigned ints of size 1 byte 
b

array(['1', '2'], dtype='<U1')

In [12]:
bb = np.array([1, 2])
bb

array([1, 2])

In [13]:
print(b.ndim,b.shape,b.size,b.dtype,b.itemsize)
print(bb.ndim,bb.shape,bb.size,bb.dtype,bb.itemsize)

1 (2,) 2 <U1 4
1 (2,) 2 int32 4


In [1]:
import cv2
import sys

imagePath = './sample/01-color_space/test.jpg'
image = cv2.imread(imagePath) #用來讀取圖片檔；並儲存成NumPy的陣列
print(image)
print(type(image))
print(image.ndim) #3
print(image.shape) #(426, 571, 3)；圖片尺寸是571x426(單位:像素) 
#NumPy陣列的前兩個維度是圖片的高度&寬度
#的三個維度是圖片的channel(RGB彩色就是3;灰階就是1)

image_1 = cv2.imread(imagePath,cv2.IMREAD_COLOR) #這是預設(忽略透明度)
image_2 = cv2.imread(imagePath,cv2.IMREAD_GRAYSCALE) #以灰階格式讀取
image_3 = cv2.imread(imagePath,cv2.IMREAD_UNCHANGED) #讀取圖片中所有的channels,包含透明度的channel

#cv2.namedWindow("This is a picture",cv2.WINDOW_NORMAL) -> 如果按最大化，圖會跟著放大佔滿視窗，比例可能因此拉寬
cv2.imshow("This is a picture",image)

#cv2.imshow("image1",image_1)
#cv2.imshow("image2",image_2)
#cv2.imshow("image3",image_3)

cv2.waitKey(0) #0代表持續等待直到使用者按下任意按鍵為止；若填入數字就會是倒數毫秒數(ms)
cv2.destroyAllWindows() #如果在程式中有許多的OpenCV視窗，而只要關閉特定的視窗時，可以改用cv2.destroyWindow('視窗名稱')


[[[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 ...

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]]
<class 'numpy.ndarray'>
3
(426, 571, 3)


In [4]:
import cv2
import sys

imagePath = './sample/01-color_space/test.jpg'
image = cv2.imread(imagePath) #用來讀取圖片檔；並儲存成NumPy的陣列
print(image)
print(type(image))
print(image.ndim) #3
print(image.shape) #(426, 571, 3)；圖片尺寸是571x426(單位:像素) 

image_1 = cv2.imread(imagePath,cv2.IMREAD_COLOR) #這是預設(忽略透明度)
image_2 = cv2.imread(imagePath,cv2.IMREAD_GRAYSCALE) #以灰階格式讀取
image_3 = cv2.imread(imagePath,cv2.IMREAD_UNCHANGED) #讀取圖片中所有的channels,包含透明度的channel

#cv2.putText(img, TEXT, (x,y), font, scale, color) 在圖上面疊字
cv2.putText(image,"Penguin!",(50,70),cv2.FONT_HERSHEY_SIMPLEX,3,(255,155,255))

#cv2.namedWindow("This is a picture",cv2.WINDOW_NORMAL) -> 如果按最大化，圖會跟著放大佔滿視窗，比例可能因此拉寬
cv2.imshow("This is a picture",image)

#將影像存成檔案
cv2.imwrite("penguin.png",image)
#cv2.imwrite("penguin_compress.png",image,[cv2.IMWRITE_PNG_COMPRESSION,9])

cv2.waitKey(0) #0代表持續等待直到使用者按下任意按鍵為止；若填入數字就會是倒數毫秒數(ms)
cv2.destroyAllWindows() #如果在程式中有許多的OpenCV視窗，而只要關閉特定的視窗時，可以改用cv2.destroyWindow('視窗名稱')


[[[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 ...

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]]
<class 'numpy.ndarray'>
3
(426, 571, 3)


In [51]:
#直線部分

import numpy as np
import cv2
img = np.zeros((256,256,3),np.uint8)
print(img,"\n")
img.fill(200) #把圖片用淺灰色填滿
print(img)

#cv2.line(影像, 開始座標, 結束座標, 顏色, 線條寬度)
cv2.line(img,(0,0),(255,255),(100,0,200),5)

#cv2.rectangle(影像, 頂點座標, 對向頂點座標, 顏色, 線條寬度) 
cv2.rectangle(img,(20,160),(120,60),(100,250,150),3)
cv2.rectangle(img,(20,50),(120,150),(100,0,150),3)
cv2.rectangle(img,(40,80),(100,140),(0,255,0),-1) #負數是實心框

#cv2.circle(影像, 圓心座標, 半徑, 顏色, 線條寬度) 
cv2.circle(img,(90,210),30,(0,255,255),3)
cv2.circle(img,(120,220),15,(255,0,0),-1)

#cv2.ellipse(影像, 中心座標, 軸長(半長軸與半短軸的長度), 旋轉角度, 起始角度, 結束角度, 顏色, 線條寬度) 
cv2.ellipse(img,(180,200),(25,55),45,0,360,(205,0,255),2)
cv2.ellipse(img,(180,200),(20,50),45,0,180,(255,0,255),-1)

cv2.imshow("My Image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]] 

[[[200 200 200]
  [200 200 200]
  [200 200 200]
  ...
  [200 200 200]
  [200 200 200]
  [200 200 200]]

 [[200 200 200]
  [200 200 200]
  [200 200 200]
  ...
  [200 200 200]
  [200 200 200]
  [200 200 200]]

 [[200 200 200]
  [200 200 200]
  [200 200 200]
  ...
  [200 200 200]
  [200 200 200]
  [200 200 200]]

 ...

 [[200 200 200]
  [200 200 200]
  [200 200 200]
  ...
  [200 200 200]
  [200 200 200]
  [200 200 200]]

 [[200 200 200]
  [200 200 200]
  [200 200 200]
  ...
  [200 200 200]
  [200 200 200]
  [200 200 200]]

 [[200 200 200]
  [200 200 200]
  [200 200 200]
  ...
  [2